### ISSUE TITLE
Add signup feature using google authentication

### ISSUE THREAD

**Issue by AkshJain99** [AkshJain99/Blogging-App#7]
Add feature in which person can be able to sign up using google credentials as we usually see in many websites

**Comment by srikeshav** [comment]
I will work on this issue

**Comment by jaindhairyahere** [comment]
Can I work on this issue? Is the issue still open?

**Comment by AkshJain99** [comment]
Yes you can proceed

**Comment by jaindhairyahere** [comment]
can you add the KWOC label and assign the me the issue?

**Comment by jaindhairyahere** [comment]
I think I have resolved the issue. How do I create a PR?

**Comment by AkshJain99** [comment]
Refer git documentation and GitHub vedio to see how can you create pull
request
